services:
  web:
    image: amazon_scrape
    logging:
      driver: syslog
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
    volumes:
      - ./data:/app/data
    ports:
      - "7000:7000"
    restart: unless-stopped

  batch:
    image: amazon_scrape
    logging:
      driver: syslog
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/app/data
      - ./html:/app/html
    entrypoint: ["uv", "run", "python"]
    command: ["/app/save_new_books.py"]
    restart: "no"
