services:
  web:
    image: amazon_scrape:latest
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "80:8000"
    restart: unless-stopped

  batch:
    image: amazon_scrape:latest
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./html:/app/html
    entrypoint: ["uv", "run", "python"]
    command: ["/app/save_new_books.py"]
    restart: "no"
