services:
  web:
    image: comp_books:latest
    build:
      context: .
    logging:
      driver: syslog
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      TZ: Asia/Tokyo
      AMAZON_AFFILIATE_TAG: postcardst-22
    volumes:
      - ./data:/app/data
    ports:
      - "7000:7000"
    restart: unless-stopped
